spring:
  application:
    name: app-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/agent_platform
    username: agent_platform_user
    password: agent_platform_password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 9094

management:
  endpoints:
    web:
      exposure:
        include: health,info